### ISSUE TITLE
MessageClassifier 黑龙 包含 MM 不准确。

### ISSUE THREAD

**Issue by sejust** [SwimmingTiger/WowBigfootClassic#8]
世界刷MM的太多了，不准确

**Comment by YihaoPeng** [comment]
https://github.com/SwimmingTiger/WowBigfootClassic/blob/17549fe3860bebc805f69f65f3c2408b51446a7b/Interface/AddOns/MessageClassifier/locale/zhCN.lua#L576-L599

嗯，我也发现了。新版本已经删掉MM了。
